recipe_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path

from recipes.views import (DeleteRecipeView, HomeView, LikeView, NewRecipeView,
                           RateView, RecipeDetailView, RecipeSearchView,
                           RecipesFromIngradientView, UpdateRecipeView)
from users.views import SignUp

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", HomeView.as_view(), name="home"),
    path(
        "ingradient/<int:pk>/", RecipesFromIngradientView.as_view(), name="ingradient"
    ),
    path("recipe/<int:pk>/", RecipeDetailView.as_view(), name="recipe_detail"),
    path("search/", RecipeSearchView.as_view(), name="search"),
    path("delete_recipe/<int:pk>/", DeleteRecipeView.as_view(), name="delete_recipe"),
    path("signup/", SignUp.as_view(), name="signup"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("new_recipe/", NewRecipeView.as_view(), name="new_recipe"),
    path("update_recipe/<int:pk>/", UpdateRecipeView.as_view(), name="update_recipe"),
    path("like/<int:pk>/", LikeView.as_view(), name="like"),
    path("rate/<int:pk>/", RateView.as_view(), name="rate"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/models.py
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.db.models import Avg
from django.db.models.functions import Coalesce
from django.utils.translation import gettext as _


# MANAGERS
class IsActiveManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_active=True)


# MODELS
class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    recipe = models.ForeignKey("recipes.Recipe", on_delete=models.CASCADE)


class Rate(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    recipe = models.ForeignKey("recipes.Recipe", on_delete=models.CASCADE)
    rate = models.IntegerField(
        validators=[MaxValueValidator(100), MinValueValidator(1)]
    )


class Recipe(models.Model):
    class DIFFICULTIES(models.IntegerChoices):
        EASY = 1, _("Easy")
        MEDIUM = 2, _("Medium")
        HARD = 3, _("Hard")

    title = models.CharField(max_length=255, verbose_name=_("title"))
    description = models.TextField(verbose_name=_("description"))
    create_time = models.DateTimeField(auto_now_add=True, verbose_name=_("create time"))
    change_time = models.DateTimeField(auto_now=True, verbose_name=_("change time"))
    view_count = models.IntegerField(default=0)
    difficulty = models.IntegerField(
        choices=DIFFICULTIES.choices, verbose_name=_("difficulty")
    )
    image = models.ImageField()

    # Relations with other models
    author = models.ForeignKey(
        User, null=True, on_delete=models.SET_NULL, verbose_name=_("author")
    )
    ingredients = models.ManyToManyField("recipes.Ingradient")
    likes = models.ManyToManyField(
        User, through=Like, related_name="likes_set", through_fields=("recipe", "user")
    )
    rates = models.ManyToManyField(
        User, through=Rate, through_fields=("recipe", "user"), related_name="rates_set"
    )
    is_active = models.BooleanField(default=True)

    # Managers
    objects = models.Manager()
    actives = IsActiveManager()

    @property
    def rate_avg(self):
        rates = Rate.objects.filter(recipe=self.pk)
        return rates.aggregate(rate__avg=Coalesce(Avg("rate"), 0))["rate__avg"]

    @property
    def rate_count(self):
        return self.rates.count()

    @property
    def like_count(self):
        return self.likes.count()

    def delete(self):
        self.is_active = False
        self.save()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("Recipe")
        verbose_name_plural = _("Recipes")


class Ingradient(models.Model):
    ingredient = models.CharField(max_length=128, verbose_name=_("ingredient"))

    def __str__(self):
        return self.ingredient

recipes/forms.py
from django import forms

from recipes.models import Recipe


class RecipesForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ["title", "image", "description", "difficulty", "ingredients"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["title"].widget.attrs["class"] = "form-control"
        self.fields["description"].widget.attrs["class"] = "form-control"
        self.fields["difficulty"].widget.attrs["class"] = "form-control"
        self.fields["ingredients"].widget.attrs["class"] = "form-control"

recipes/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import F, Q
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import CreateView, DeleteView, UpdateView

from recipes.forms import RecipesForm
from recipes.generics import GenericRecipeListView
from recipes.mixins import OwnerPermissionMixin
from recipes.models import Ingradient, Like, Rate, Recipe


class HomeView(GenericRecipeListView):
    recipe_queryset = Recipe.actives.all()


class RecipesFromIngradientView(GenericRecipeListView):
    def get_recipe_queryset(self):
        return Recipe.actives.filter(ingredients__pk=self.kwargs.get("pk"))


class RecipeSearchView(GenericRecipeListView):
    def get_recipe_queryset(self):
        # get searched ingradients
        search_words = [x.strip() for x in self.request.GET.get("q").split(",")]
        or_queris = Q()
        for words in search_words:
            or_queris = or_queris | Q(ingredient__icontains=words)
        ingrads = Ingradient.objects.filter(or_queris)

        # get recipes which has all the ingradient in same time
        recipes = Recipe.objects.none()
        if ingrads.count() != 0:
            recipes = ingrads.first().recipe_set.all()
            for ingrad in ingrads[1:]:
                recipes = recipes.intersection(ingrad.recipe_set.all())

        # search from title
        if recipes.count() == 0:
            or_queris = Q()
            for words in search_words:
                or_queris = or_queris | Q(title__icontains=words)
                or_queris = or_queris | Q(description__icontains=words)
            recipes = Recipe.objects.filter(or_queris)

        return recipes


class DeleteRecipeView(OwnerPermissionMixin, DeleteView):
    model = Recipe
    success_url = reverse_lazy("home")


@method_decorator(login_required, name="dispatch")
class NewRecipeView(CreateView):
    model = Recipe
    form_class = RecipesForm
    success_url = reverse_lazy("home")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


@method_decorator(login_required, name="dispatch")
class UpdateRecipeView(OwnerPermissionMixin, UpdateView):
    model = Recipe
    form_class = RecipesForm

    def form_valid(self, form):
        obj = form.save(commit=True)
        return redirect("recipe_detail", obj.id)


class RecipeDetailView(View):
    def get(self, request, *args, **kwargs):
        self.recipe = get_object_or_404(Recipe, pk=kwargs.get("pk"), is_active=True)
        self.recipe.view_count = F("view_count") + 1
        self.recipe.save()

        context = {"recipe": self.recipe, **self.__get_liked_and_rate()}
        return render(request, "recipes/recipe_detail.html", context)

    def __get_liked_and_rate(self):
        if not self.request.user.is_authenticated:
            return {}

        is_rated = True
        rate_point = 0
        try:
            rate_point = Rate.objects.get(
                user=self.request.user, recipe=self.recipe
            ).rate
        except Rate.DoesNotExist:
            is_rated = False

        return {
            "is_liked": Like.objects.filter(user=self.request.user, recipe=self.recipe),
            "is_rated": is_rated,
            "rate_point": rate_point,
        }


# User interaction Views


@method_decorator(login_required, name="dispatch")
class LikeView(View):
    def get(self, request, pk):
        recipe = get_object_or_404(Recipe, pk=pk)
        try:
            Like.objects.get(user=request.user, recipe=recipe).delete()
        except Like.DoesNotExist:
            Like.objects.create(user=request.user, recipe=recipe)

        return redirect("recipe_detail", pk=pk)


@method_decorator(login_required, name="dispatch")
class RateView(View):
    def __validate(self, pk):
        rate = int(self.request.POST.get("rate"))
        if not rate or rate < 0 or rate > 5:
            return redirect("recipe_detail", pk=pk)

    def post(self, request, pk):
        recipe = get_object_or_404(Recipe, pk=pk)
        self.__validate(pk)

        Rate.objects.update_or_create(
            user=request.user,
            recipe=recipe,
            defaults={"rate": request.POST.get("rate")},
        )

        return redirect("recipe_detail", pk=pk)

templates/recipes/recipe_confirm_delete.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    <p>{% trans "Are you sure you want to delete?"  %}</p>
    <input type="submit" value="Delete">
  </form>
{% endblock %}

templates/recipes/recipe_detail.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %}
  {{ recepie }}
{% endblock %}

{% block content %}
  
  <h1>{{ recipe }}</h1>
  
  <div class="card-top">
    <div class="item">
      <img alt="" src="{% static 'img/knife.png' %}"/>
      {{ recipe.author }}
    </div>
    <div class="item">
      <img alt="" src="{% static 'img/muscles.png' %}"/>
      {{ recipe.get_difficulty_display }}
    </div>
    <div class="item">
      <img alt="" src="{% static 'img/circular-clock.png' %}"/>
      {{ recipe.create_time|date:"d/m/Y"  }}
    </div>
  </div>
  {% if recipe.author == request.user%}
    <a href="{% url 'update_recipe' pk=recipe.pk %}">Edit the recipe</a>
    <br>
    <a href="{% url 'delete_recipe' pk=recipe.pk %}">Delete</a>
  {% endif %}
  <br/>

  <p>
    <img class="food-img" alt="{{ recipe }}" src="{{ recipe.image.url }}"/>
  </p>

  {% if request.user.is_authenticated  %}
    <a href="{% url 'like' pk=recipe.pk %}">
      <button type="button" class="btn btn-success">
        {% if is_liked %}
          {% trans "You Have Liked"  %} ({{ recipe.like_count }})
        {% else %}
          {% trans "Like"  %} ({{ recipe.like_count }})
        {% endif %}
      </button>
    </a>
  {% endif %}

  <h2>
    {% trans "Ingredients"  %}
  </h2>
  <ul>
    {% for ingredient in recipe.ingredients.all %}
      <li>
        {{ ingredient }}
      </li>
    {% endfor %}
  </ul>
  <h2>
    {% trans "Description"  %}
  </h2>
  <p>
    {{ recipe.description }}
  </p>
  <br>

  {% if request.user.is_authenticated  %}
    <form action="{% url 'rate' pk=recipe.pk %}" method="post">
      {% csrf_token %}
      {% if is_rated %}
        {% trans "You have rated"  %} ({{rate_point}})
      {% endif %}
      <select name="rate" class="form-control" style="width:50px;">
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
      </select>

      
      <input class="btn btn-primary" type="submit"
        value="
                    {% if is_rated %}
                    Rate Again
                    {% else %}
                    Rate
                    {% endif %}
                    ">
    </form>
  {% endif %}




{% endblock %}

templates/recipes/recipe_form.html
{% extends 'base.html' %}

{% block content %}
  <h2>SignUp</h2>
  <form method="post"  enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary" type="submit">Share The Recipe</button>
  </form>

{% endblock %}

templates/recipes/recipe_list.html
{% extends 'base.html' %}
{% load i18n %}


{% block content %}
  <div class="col-md-8">
    {% for recipe in recipes %}
      <div class="recipe-block">
        <h2><a href="{% url 'recipe_detail' pk=recipe.pk %}">{{ recipe }}</a></h2>
        <img class="food-img" alt="{{ recipe }}" src="{{ recipe.image.url }}"/>

        <p>{{ recipe.description | truncatechars:200}}</p>

        <div class="recipe-block-footer">
          {{ recipe.create_time | date:"d/m/Y"  }} . {{ recipe.rate_avg }}/5 ({{ recipe.rate_count }}) . {{ recipe.like_count }} {% trans "likes . by"  %} {{ recipe.author }}
          {% if recipe.author == request.user%}
            <a href="{% url 'update_recipe' pk=recipe.pk %}">{% trans "Edit"  %}</a>
          {% endif %}
        </div>
      </div>
    {% endfor %}

    <div class="pageination-container">
      {% if recipes.has_previous %}
        <a href="?page={{ recipes.previous_page_number }}{% if request.GET.q %}&&q={{ request.GET.q }}{% endif %}">
          <button class="btn btn-default">
            {% trans "Previous Page"  %}
          </button>
        </a>
      {% endif %}

      {% if recipes.has_next %}
        <a href="
                 ?page={{ recipes.next_page_number }}{% if request.GET.q %}&&q={{ request.GET.q }}{% endif %}
                 ">
          <button class="btn btn-default">
            {% trans "Next Page"  %}
          </button>
        </a>
      {% endif %}

      <p class="current">
        {% trans "Page"  %} {{ recipes.number }} {% trans "of"  %} {{ recipes.paginator.num_pages }}.
      </p>
    </div>

  </div>


  <div class="col-md-4">
    <div class="recipe-block">
      <h3>{% trans "Search"  %}</h3>

      <form action="{% url 'search' %}" method="get">
        <input type="text" name ="q"  placeholder="egg, potato ...." value="{{request.GET.q}}"></input>
        <input class="btn btn-primary" type="submit" value="Search">
      </form>
      <br>
      <p>{% trans "Search ingradients between comma "  %}</p>
      <p>{% trans "(eg. \"egg, potato\" will get if recipe has egg and potato <b>same</b> time)"  %}</p>
      <p>{% trans "If not find any recipe, search from in title and content."  %}</p>
    </div>

    <div class="recipe-block">
      <h3>{% trans "Top Used Ingredients"  %}</h3>
      <ul>
        {% for ingredient in most_used_ingredients %}
          {% if ingredient.total %}
            <li>
              <a href="{% url "ingradient" pk=ingredient.ingredients__pk %}">
                {{ ingredient.ingredients__ingredient }}
              </a>({{ ingredient.total }})

            </li>
          {% endif %}
        {% endfor %}

      </ul>
    </div>
  </div>
  
{% endblock %}

{% block extra_js %}
{% endblock %}